fixed fcron

diff --git a/core/fcron/spkgbuild b/core/fcron/spkgbuild
--- a/core/fcron/spkgbuild
+++ b/core/fcron/spkgbuild
@@ -1,30 +1,94 @@
-# description : scheduling program
-# depends : nano linux-pam
+# description   : The Fcron package contains a periodical command scheduler which aims at replacing Vixie Cron
+# depends       : none
 
 name=fcron
-version=3.4.0
+version=3.4.0    
 release=1
+source="http://fcron.free.fr/archives/fcron-3.4.0.src.tar.gz"
 
-backup="var/spool/fcron/systab.orig"
-source="http://fcron.free.fr/archives/$name-$version.src.tar.gz\
-	systab.orig
-	run-parts"
 options="!checksum"
 
 build() {
-	cd $name-$version
+        cd *
+	mkdir $PKG/etc
+cat >> $PKG/etc/syslog.conf << "EOF"
+# Begin fcron addition to /etc/syslog.conf
+
+cron.* -/var/log/cron.log
+
+# End fcron addition
+EOF
+	mkdir -pv $PKG/etc/pam.d
 	./configure --prefix=/usr          \
             --sysconfdir=/etc      \
             --localstatedir=/var   \
             --without-sendmail     \
             --with-boot-install=no \
-            --with-systemdsystemunitdir=no\
-            --with-editor=/usr/bin/nano
-        make
-        make DESTDIR=$PKG install
+            --with-systemdsystemunitdir=no \
+            --with-editor=/usr/bin/nano 
+	make
+	make DESTDIR=$PKG install
+
 	mkdir -pv $PKG/usr/bin
-	install -Dm644 $SRC/run-parts $PKG/usr/bin/run-parts
-	mkdir -pv $PKG/var/spool/fcron
-	install -Dm644 $SRC/systab.orig $PKG/var/spool/fcron/systab.orig	
-	create_startup_directories fcron_start K08fcron S08fcron $SRC $PKG
+cat > $PKG/usr/bin/run-parts << "EOF" &&
+#!/bin/sh
+# run-parts:  Runs all the scripts found in a directory.
+# from Slackware, by Patrick J. Volkerding with ideas borrowed
+# from the Red Hat and Debian versions of this utility.
+
+# keep going when something fails
+set +e
+
+if [ $# -lt 1 ]; then
+  echo "Usage: run-parts <directory>"
+  exit 1
+fi
+
+if [ ! -d $1 ]; then
+  echo "Not a directory: $1"
+  echo "Usage: run-parts <directory>"
+  exit 1
+fi
+
+# There are several types of files that we would like to
+# ignore automatically, as they are likely to be backups
+# of other scripts:
+IGNORE_SUFFIXES="~ ^ , .bak .new .rpmsave .rpmorig .rpmnew .swp"
+
+# Main loop:
+for SCRIPT in $1/* ; do
+  # If this is not a regular file, skip it:
+  if [ ! -f $SCRIPT ]; then
+    continue
+  fi
+  # Determine if this file should be skipped by suffix:
+  SKIP=false
+  for SUFFIX in $IGNORE_SUFFIXES ; do
+    if [ ! "$(basename $SCRIPT $SUFFIX)" = "$(basename $SCRIPT)" ]; then
+      SKIP=true
+      break
+    fi
+  done
+  if [ "$SKIP" = "true" ]; then
+    continue
+  fi
+  # If we've made it this far, then run the script if it's executable:
+  if [ -x $SCRIPT ]; then
+    $SCRIPT || echo "$SCRIPT failed."
+  fi
+done
+
+exit 0
+EOF
+chmod -v 755 $PKG/usr/bin/run-parts
+
+install -vdm754 $PKG/etc/cron.{hourly,daily,weekly,monthly}
+
+mkdir -pv $PKG/var/spool/fcron
+cat > $PKG/var/spool/fcron/systab.orig << "EOF"
+&bootrun 01 * * * * root run-parts /etc/cron.hourly
+&bootrun 02 4 * * * root run-parts /etc/cron.daily
+&bootrun 22 4 * * 0 root run-parts /etc/cron.weekly
+&bootrun 42 4 1 * * root run-parts /etc/cron.monthly
+EOF
 }
